services:
  # MongoDB Service for Question Service
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Seed MongoDB server with sample questions
  mongo_seed:
    image: mongo:latest
    container_name: mongo_seed
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
      - mongo-seed:/seed_set
    command: /mongo-seed/import.sh
    networks:
      - app-network

  # QuestionService
  question-service:
    build: ./QuestionService
    container_name: question-service
    ports:
      - "4000:3000"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  # MongoDB Service for UserService 
  mongo_user:
    image: mongo:latest
    container_name: mongo_user
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27018:27017" 
    volumes:
      - mongo-user-data:/data/db
    networks:
      - app-network
    
  # UserService
  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - DB_CLOUD_URI=mongodb+srv://admin:admin@cluster0.ie5m1.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DB_LOCAL_URI=mongodb://root:example@mongo_user:27017
      - ENV=DEV
      - JWT_SECRET=you-can-replace-this-with-your-own-secret
    depends_on:
      - mongo_user
    networks:
      - app-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:5173"
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local
  mongo-seed:
    driver: local
  mongo-user-data:
    driver: local
  

networks:
  app-network:
    driver: bridge
