openapi: 3.0.0
info:
  title: Question Service API
  description: API for fetching single or multiple questions from a database.
  version: 1.0.0

paths:
  /question:
    get:
      summary: Fetch a single question by ID
      tags:
        - Questions
      parameters:
        - in: query
          name: questionId
          schema:
            type: integer
          required: true
          description: The ID of the question to fetch
      responses:
        200:
          description: A single question from the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        400:
          description: Invalid question ID provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid Question ID"
        500:
          description: Server error

  /questions:
    get:
      summary: Fetch multiple questions based on filters
      tags:
        - Questions
      parameters:
        - in: query
          name: topic
          schema:
            type: string
          required: false
          description: Filter questions by topic
        - in: query
          name: difficulty
          schema:
            type: string
            enum: [Easy, Medium, Hard]
          required: false
          description: Filter questions by difficulty
      responses:
        200:
          description: A list of questions that match the filters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
        500:
          description: Server error

components:
  schemas:
    Question:
      type: object
      properties:
        questionId:
          type: integer
          example: 2
        questionTitle:
          type: string
          example: "Linked List Cycle Detection"
        questionDescription:
          type: string
          example: "Implement a function to detect if a linked list contains a cycle."
        questionCategories:
          type: array
          items:
            type: string
          example: ["Data Structures", "Algorithms"]
        questionComplexity:
          type: string
          example: "Easy"
        link:
          type: string
          format: uri
          example: "https://leetcode.com/problems/linked-list-cycle/"

  responses:
    InvalidQuestionID:
      description: Invalid Question ID provided
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid Question ID"
    ServerError:
      description: A server error occurred.
