apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gcr.io/peerprep-438713/user-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_LOCAL_URI
          value: mongodb://mongo-user-service:27017
        - name: ENV
          value: DEV
        - name: JWT_SECRET
          value: you-can-replace-this-with-your-own-secret
