apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-user
  template:
    metadata:
      labels:
        app: mongo-user
    spec:
      containers:
      - name: mongo-user
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        volumeMounts:
        - name: mongo-user-storage
          mountPath: /data/db
      volumes:
      - name: mongo-user-storage
        persistentVolumeClaim:
          claimName: mongo-user-pvc
