apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service
        image: gcr.io/peerprep-438713/collaboration-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002