name: CI - Build and Push Docker Images

on:
  push:
    branches:
      - main
      - kubernetes-config

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Submit Cloud Build
      run: gcloud builds submit --config=cloudbuild.yaml ../../
