name: CI/CD - Build and Deploy

on:
  push:
    branches:
      - main
      - kubernetes-config

jobs:
  ci:
    name: Build and Push Docker Images

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Submit Cloud Build
        run: gcloud builds submit --config=cloudbuild.yaml .

  cd:
    name: Deploy to GKE

    runs-on: ubuntu-latest

    needs: ci
    
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
  
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
  
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }}

      - name: Set kubectl context
        run: kubectl config set-context $(kubectl config current-context) --namespace=default

      - name: Deploy to GKE
        run: kubectl apply -f k8s/
