name: CI - Build and Push Docker Images to GCR

on:
  push:
    branches:
      - main
      - kubernetes-config

jobs:
  build:
    name: Build and Push Docker Images

    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Submit Cloud Build
      run: gcloud builds submit --config=cloudbuild.yaml .
