name: Test Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ChatService, QuestionService, UserService/user-service, CollaborationService, MatchingService]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./${{ matrix.service }}

      - name: Run test coverage
        run: npm run test:coverage
        working-directory: ./${{ matrix.service }}

      - name: Set sanitized service name
        run: echo "SANITIZED_SERVICE_NAME=${{ matrix.service }}" | sed 's|/|_|g' >> $GITHUB_ENV

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
           name: ${{ env.SANITIZED_SERVICE_NAME }}-coverage
           path: ./${{ matrix.service }}/coverage/

  merge-coverage:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download coverage reports
          uses: actions/download-artifact@v4
          with:
            path: ./coverage-reports

        - name: Install nyc
          run: npm install -g nyc

        - name: Merge coverage reports with nyc
          run: |
            mkdir -p .nyc_output
            cp -r ./coverage-reports/**/ .nyc_output/
            nyc merge .nyc_output ./.nyc_output/coverage.json

        - name: Generate HTML report
          run: nyc report --reporter=html

        - name: Upload HTML report
          uses: actions/upload-artifact@v4
          with:
            name: html-coverage-report
            path: coverage